{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0eedca89-5906-445c-b3b4-cbb82283629a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"650\"\n",
       "            src=\"http://127.0.0.1:8050/\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x25687ae3b50>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "from dash import Dash, html, dcc, callback, Output, Input\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "import pandas as pd\n",
    "\n",
    "df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminder_unfiltered.csv')\n",
    "\n",
    "def create_bar_chart(df, year):\n",
    " dff = df[df.year == year]\n",
    " top_15 = dff.groupby('country')['pop'].sum().nlargest(15).reset_index()\n",
    " fig = go.Figure(data=go.Bar(x=top_15['country'], y=top_15['pop']),\n",
    " layout=go.Layout(title=f'Столбчатая диаграмма ({year})', xaxis=dict(title='Страна'), yaxis=dict(title='Популяция')))\n",
    " return fig\n",
    "\n",
    "def create_pie_chart(df, year):\n",
    " dff = df[df.year == year]\n",
    " continent_pop = dff.groupby('continent')['pop'].sum().reset_index()\n",
    " fig = go.Figure(data=go.Pie(labels=continent_pop['continent'], values=continent_pop['pop']))\n",
    " return fig\n",
    "\n",
    "app = Dash(__name__)\n",
    "server=app.server\n",
    "\n",
    "app.layout = html.Div([\n",
    "html.H1(children='Title of Dash App', style={'textAlign': 'center'}),\n",
    "\n",
    "dcc.Tabs(id='tabs', value='scatter', children=[\n",
    "dcc.Tab(label='Линейная диаграмма', value='scatter', children=[\n",
    "dcc.Dropdown(options=[{'label': country, 'value': country} for country in df.country.unique()],value=['Canada'], multi=True, id='scatter-dropdown-selection'),\n",
    "dcc.Dropdown(options=[{'label': col, 'value': col} for col in df.columns[3:]],value='pop', id='scatter-y-axis-selection')]),\n",
    "\n",
    "dcc.Tab(label='Пузырьковая диаграмма', value='bubble', children=[\n",
    "dcc.Dropdown(options=[{'label': col, 'value': col} for col in df.columns[3:]],value='gdpPercap', id='bubble-x-axis-selection'),\n",
    "dcc.Dropdown(options=[{'label': col, 'value': col} for col in df.columns[3:]],value='pop', id='bubble-y-axis-selection'),\n",
    "dcc.Dropdown(options=[{'label': col, 'value': col} for col in df.columns[3:]],value='lifeExp', id='bubble-radius-selection'),\n",
    "dcc.Dropdown(options=[{'label': year, 'value': year} for year in df.year.unique()],value=df.year.min(), id='bubble-year-selection')]),\n",
    "    \n",
    "dcc.Tab(label='Стобчатая диаграмма', value='top-15', children=[\n",
    "dcc.Dropdown(options=[{'label': year, 'value': year} for year in df.year.unique()],value=df.year.min(), id='top15-year-selection')]),\n",
    "    \n",
    "dcc.Tab(label='Круговая диаграмма', value='population-by-continent', children=[\n",
    "dcc.Dropdown(options=[{'label': year, 'value': year} for year in df.year.unique()],value=df.year.min(), id='continent-year-selection')])]),\n",
    "dcc.Graph(id='graph-content'),\n",
    "html.H3(id='graph-title')\n",
    "])\n",
    "\n",
    "@app.callback(\n",
    "Output('graph-content', 'figure'),\n",
    "Output('graph-title', 'children',allow_duplicate=True),\n",
    "Input('tabs', 'value'),\n",
    "Input('scatter-dropdown-selection', 'value'),\n",
    "Input('scatter-y-axis-selection', 'value'),\n",
    "Input('bubble-x-axis-selection', 'value'),\n",
    "Input('bubble-y-axis-selection', 'value'),\n",
    "Input('bubble-radius-selection', 'value'),\n",
    "Input('bubble-year-selection', 'value'),\n",
    "Input('top15-year-selection', 'value'),\n",
    "Input('continent-year-selection', 'value'),\n",
    "prevent_initial_call='initial_duplicate'\n",
    ")\n",
    "def update_graph(selected_tab, scatter_selected_countries, scatter_selected_y,\n",
    " bubble_selected_x, bubble_selected_y, bubble_selected_radius,\n",
    " bubble_selected_year, top15_selected_year,continent_selected_year):\n",
    " if selected_tab == 'scatter':\n",
    "  dff_scatter = df[df.country.isin(scatter_selected_countries)]\n",
    "  fig_scatter = px.line(dff_scatter, x='year', y=scatter_selected_y, color='country')\n",
    "  return fig_scatter, f'Selected Tab: {selected_tab}, Selected Countries: {\", \".join(scatter_selected_countries)}, Y-Axis: {scatter_selected_y}'\n",
    "\n",
    " elif selected_tab == 'bubble':\n",
    "  dff_bubble = df[df.year == bubble_selected_year]\n",
    "  fig_bubble = px.scatter(dff_bubble, x=bubble_selected_x, y=bubble_selected_y, size=bubble_selected_radius)\n",
    "  return fig_bubble, f'Selected Tab: {selected_tab}, X-Axis: {bubble_selected_x}, Y-Axis: {bubble_selected_y}, Bubble Size: {bubble_selected_radius}, Year: {bubble_selected_year}'\n",
    "\n",
    " elif selected_tab == 'top-15':\n",
    "  dff_top15 = df[df.year == top15_selected_year]\n",
    "  fig_top15 = create_bar_chart(dff_top15, top15_selected_year)\n",
    "  return fig_top15, f'Selected Tab: {selected_tab}, Year: {top15_selected_year}'\n",
    "    \n",
    " elif selected_tab == 'population-by-continent':\n",
    "  dff_continent = df[df.year == continent_selected_year]\n",
    "  fig_continent = create_pie_chart(dff_continent, continent_selected_year)\n",
    "  return fig_continent, f'Selected Tab: {selected_tab}, Year: {continent_selected_year}'\n",
    "@app.callback(\n",
    "Output('graph-title', 'children'),\n",
    "Input('tabs', 'value'),\n",
    "Input('scatter-dropdown-selection', 'value'),\n",
    "Input('scatter-y-axis-selection', 'value'),\n",
    "Input('bubble-x-axis-selection', 'value'),\n",
    "Input('bubble-y-axis-selection', 'value'),\n",
    "Input('bubble-radius-selection', 'value'),\n",
    "Input('bubble-year-selection', 'value'),\n",
    "Input('top15-year-selection', 'value'),\n",
    "Input('continent-year-selection', 'value'),\n",
    ")\n",
    "def update_graph_title(selected_tab, scatter_selected_countries, scatter_selected_y,\n",
    " bubble_selected_x, bubble_selected_y, bubble_selected_radius,\n",
    " bubble_selected_year, top15_selected_year, continent_selected_year):\n",
    " if selected_tab == 'scatter':\n",
    "  return f'Selected Tab: {selected_tab}, Selected Countries: {\", \".join(scatter_selected_countries)}, Y-Axis: {scatter_selected_y}'\n",
    "\n",
    " elif selected_tab == 'bubble':\n",
    "  return f'Selected Tab: {selected_tab}, X-Axis: {bubble_selected_x}, Y-Axis: {bubble_selected_y}, Bubble Size: {bubble_selected_radius}, Year: {bubble_selected_year}'\n",
    "\n",
    " elif selected_tab == 'top-15':\n",
    "  return f'Selected Tab: {selected_tab}, Year: {top15_selected_year}'\n",
    "    \n",
    " elif selected_tab == 'population-by-continent':\n",
    "  return f'Selected Tab: {selected_tab}, Year: {continent_selected_year}'\n",
    "    \n",
    "if __name__ == '__main__':\n",
    " app.run_server(debug=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8c05bdc1-079e-4c2c-9ef7-7c134091de79",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
